#!/bin/bash

_pv.suffix() { echo $$; }

_pv.fnname()
{
	local fnlevel=3;
    echo "${FUNCNAME[$fnlevel]"
}

_pv.name()
{
	local pvs=$(_pv.suffix);
	local var=$(_pv.fnname);
	echo $var$pvs	
}

privar()
{
	local pvarname=$(_pv.name)
	echo $pvarname
}

. uts.unit.shi

if tst.active; then

	tst.null() { echo ""; }

	function test.privar()
	{
		private() { privar; }
		local -n testvar1=$(private);
		local -n testvar2=$(private);

		local val1=$testvar1;
		assert


	}

	tst.run;
fi
